name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v5
            - name: List and Read file
              run: |
                echo "My first github action workflow"
                ls -ltra
                cat README.md
            - name: Generate ASCII Artwork
              run:  cowsay -f tiger "Run for Cover, I am a TIGER....Saurav" >> tiger.txt

           # - name : List files
           #   run: ls
            # run: cat README.md
            