name: Hello World

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: echo "Hello, world!"

  test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: echo "Hello, world!"

  Deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: echo "Hello, world!"
