name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v5

            - name: List files
              run: ls -ltra
            - name: Execute shell script
              run:  ./ascii-script.sh 
  

            